// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Account struct {
	ID       int64     `db:"id"`
	Owner    string    `db:"owner"`
	Balance  int64     `db:"balance"`
	Currency string    `db:"currency"`
	CreateAt time.Time `db:"create_at"`
}

type Entry struct {
	ID        int64     `db:"id"`
	AccountID int64     `db:"account_id"`
	Amount    int64     `db:"amount"`
	CreateAt  time.Time `db:"create_at"`
}

type Transfer struct {
	ID        int64     `db:"id"`
	FromAccID int64     `db:"from_acc_id"`
	ToAccID   int64     `db:"to_acc_id"`
	Amount    int64     `db:"amount"`
	CreateAt  time.Time `db:"create_at"`
}
